# Generated by Django 5.2.4 on 2025-09-16 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0001_initial'),
        ('masterdata', '0001_initial'),
        ('project_creation', '0001_initial'),
        ('roles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalbudgetrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_requests_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='additionalbudgetrequest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='project_creation.project'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetpolicy',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_policy', to='project_creation.project'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='project_creation.project'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cr_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cr_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='project_creation.project'),
        ),
        migrations.AddField(
            model_name='notification',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='project_creation.project'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectestimation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectestimation',
            name='estimation_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimations_provided', to='roles.userrole'),
        ),
        migrations.AddField(
            model_name='projectestimation',
            name='estimation_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimations_reviewed', to='roles.userrole'),
        ),
        migrations.AddField(
            model_name='projectestimation',
            name='estimation_review_by_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_estimations', to='project_creation.client'),
        ),
        migrations.AddField(
            model_name='projectestimation',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimations_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectestimation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimations', to='project_creation.project'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='estimation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='budget.projectestimation'),
        ),
        migrations.AddField(
            model_name='projectpaymentmilestone',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestone_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectpaymentmilestone',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestone_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectpaymenttracking',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectpaymenttracking',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectpaymenttracking',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='project_creation.project'),
        ),
        migrations.AddField(
            model_name='projectpaymenttracking',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='masterdata.masterdata'),
        ),
        migrations.AddField(
            model_name='projectpaymentmilestone',
            name='payment_tracking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='budget.projectpaymenttracking'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_tracking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='budget.projectpaymenttracking'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='payment_tracking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='budget.projectpaymenttracking'),
        ),
        migrations.AddField(
            model_name='hold',
            name='payment_tracking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='budget.projectpaymenttracking'),
        ),
        migrations.AddField(
            model_name='additionalbudgetrequest',
            name='payment_tracking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_requests', to='budget.projectpaymenttracking'),
        ),
    ]
