# Generated by Django 5.2.4 on 2025-09-17 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_initial'),
        ('project_creation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpaymenttracking',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='project_creation.project'),
        ),
    ]
