# Generated by Django 5.2.4 on 2025-09-17 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_projectpaymenttracking_project'),
        ('project_creation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpaymenttracking',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='project_creation.project'),
            preserve_default=False,
        ),
    ]
