# Generated by Django 5.2.4 on 2025-09-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_alter_projectpaymenttracking_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='hold',
            name='hold_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
