# Generated by Django 5.2.4 on 2025-09-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_hold_hold_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpaymenttracking',
            name='is_payout_manual',
            field=models.BooleanField(default=False, help_text='True if payout was manually set'),
        ),
    ]
