# Generated by Django 5.2.4 on 2025-09-17 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_details', '0003_bankdetails_is_active_alter_bankdetails_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetails',
            name='resource',
        ),
    ]
