# Generated by Django 5.2.4 on 2025-09-16 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('organisation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('organisation_name', models.CharField(max_length=255, unique=True)),
                ('organisation_mail', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisations_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisations_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('organisation_name', 'organisation_mail')},
            },
        ),
    ]
