# Generated by Django 5.2.4 on 2025-09-16 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255, unique=True)),
                ('category_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_resource', models.CharField(choices=[('Freelance', 'Freelance'), ('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract'), ('Intern', 'Intern'), ('Consultant', 'Consultant'), ('Temporary', 'Temporary'), ('Vendor', 'Vendor'), ('Outsourced', 'Outsourced'), ('Apprentice', 'Apprentice'), ('Other', 'Other')], max_length=50)),
                ('contact_details', models.CharField(blank=True, max_length=100, null=True)),
                ('pan', models.CharField(blank=True, max_length=15, null=True)),
                ('gst', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('work_location', models.CharField(blank=True, max_length=100, null=True)),
                ('work_type', models.CharField(choices=[('On-site', 'On-site'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('Shift-based', 'Shift-based'), ('Field Work', 'Field Work'), ('Project-based', 'Project-based'), ('On-call', 'On-call'), ('Travel-intensive', 'Travel-intensive'), ('Flexible Hours', 'Flexible Hours'), ('Training', 'Training')], max_length=50)),
                ('experience', models.CharField(blank=True, max_length=50, null=True)),
                ('skill_set', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='masterdata.category')),
                ('name_of_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
