# Generated by Django 5.2.4 on 2025-09-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_alter_masterdata_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdata',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='masterdata',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
