# Generated by Django 5.2.4 on 2025-08-13 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
    ]



def create_new_permissions(apps, schema_editor):
    Permission = apps.get_model('roles', 'Permission')

    permissions = [
        "create_users", "update_users", "delete_users", "view_users",
        "create_project", "update_project", "delete_project", "view_project",
        "create_organization", "update_organization", "delete_organization", "view_organization",
        "create_budget", "update_budget", "delete_budget", "view_budget",
        "create_PaymentTracking", "update_PaymentTracking", "delete_PaymentTracking", "view_PaymentTracking", 
        "create_roles", "update_roles", "delete_roles", "view_roles",
        "create_masterdata", "update_masterdata", "delete_masterdata", "view_masterdata",
        "create_bankdetails", "update_bankdetails", "delete_bankdetails", "view_bankdetails",
        "create_budget_estimation", "update_budget_estimation", "delete_budget_estimation", "view_budget_estimation",
        
    ]
    




    for perm in permissions:
        Permission.objects.get_or_create(name=perm)


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),  # Make sure the dependency is correct
    ]

    operations = [
        migrations.RunPython(create_new_permissions),
    ]
# this is the migration file


